### ISSUE TITLE
Project Checkpoint 1 Complete

### ISSUE THREAD

**Issue by esajdak** [esajdak/customCrafts#2]
@pawaitemadisoncollege Project checkpoint is ready for review. (Was unsure if application flow and database design were due for this as well though)?

Also updated my time log to include some more specifics, let me know what you think of the updates. 
Thanks!

**Comment by pawaitemadisoncollege** [comment]
Very nice job with your work so far @esajdak ! It's clear that you've put some good time and thought into this already! 

I think your project is sized very well for the MVP.

- [x] Edit/Delete Item story: "As a registered user, I want to be able to update other users when my items are sold out or have a price update." Should this be **items** instead of **users** or is this referring to a type of notification that will go out to update users?
- [ ] Am I correct that actual checkout/payment is out of scope for this version? Will the checkout button be used for accounting purposes only in this version (meaning quantity would decrease and income would be tallied)?
- [ ] Have you thought at all about an api/web service to use in your project? If not, a couple ideas: javamail api if you need to/want to send any emails from the system, or perhaps a sales tax calculator that determines sales tax based on address?
- [ ] What do you think about using a little table or multiple lines when there are multiple tasks and times in a given week?

**Comment by esajdak** [comment]
Sorry, forgot to reply to this (will close after replying)
1. I updated my user story, that was a typo.
2. I haven't looked into how hard it would be to get checkout/payment for this project. I heard someone mention that it's pretty difficult to implement when deploying so I may skip that but if I have time/capability I definitely would like to look into that.
3. I haven't looked into api options much yet- but I do like the idea of the tax calculator.
4. I somehow missed this, and haven't been implementing your suggestion but will look into further improving my time log in the coming weeks.
