### ISSUE TITLE
Week 4 Exercise

### ISSUE THREAD

**Issue by esajdak** [esajdak/customCrafts#3]
@pawaitemadisoncollege Week 4 exercise is ready to be checked

**Comment by pawaitemadisoncollege** [comment]
Great job!

- [x] You'll likely notice, if you haven't already, that writing a Dao for each entity will be very repetitive - watch for the abstract/generic dao to be introduced in the coming week and plan to use it in your project so that you can use a single dao! Note that you will still have unit tests each for each entity(dao) to make sure that annotations and database relationships are set up correctly.
- [x] Verifying the entities are saved/updated/inserted correctly can be more thorough by implementing and using equals() on each entity - refer to the video Comparing Hibernate Entities with equals in week 5 for more detail.  An example of using that equals method in a unit test would be something like `assertTrue(expectedUser.equals(actualUser));` so that you don't have to compare each instance var/column manually like this: https://github.com/esajdak/customCrafts/blob/3e31427e64c285fea64eaf46cf182e878b6ff863/src/main/test/java/edu/matc/persistence/UserDaoTest.java#L55.
- [x] Here is that filepath issue: https://github.com/esajdak/customCrafts/blob/3e31427e64c285fea64eaf46cf182e878b6ff863/src/main/resources/log4j2.properties#L21 and https://github.com/esajdak/customCrafts/blob/3e31427e64c285fea64eaf46cf182e878b6ff863/src/main/resources/log4j2.properties#L30 have references to `${filepath}` but here we have filname instead: https://github.com/esajdak/customCrafts/blob/3e31427e64c285fea64eaf46cf182e878b6ff863/src/main/resources/log4j2.properties#L2
