### ISSUE TITLE
Project checkpoint #2

### ISSUE THREAD

**Issue by esajdak** [esajdak/customCrafts#7]
@pawaitemadisoncollege Checkpoint 2 ready for review.

**Comment by pawaitemadisoncollege** [comment]
@esajdak You are doing a great job making consistent progress on your indie project. That's what checkpoint 2 is really about and you are definitely hitting the mark!

- [ ] Your database design looks solid; remember that you will also need a role table for tomcat's authentication/authorization.  You can easily add this as part of week 7. More details in my 9/30 post in #indie-project in slack.
- [x] Remember to replace the stacktrace dumps and printlns that snuck in with the database class with log statements. https://github.com/esajdak/customCrafts/blob/e87b8bba8dca5ceb89fb77929d7714738c7bc768/src/main/test/java/edu/matc/test/util/Database.java#L44-L48 and https://github.com/esajdak/customCrafts/blob/e87b8bba8dca5ceb89fb77929d7714738c7bc768/src/main/test/java/edu/matc/test/util/Database.java#L81
- [x] be careful with userids and passwords that might easily be found in github.  Adding some of these types of files to .gitignore will help, but since git already IS tracking the file, there will be a bit of extra work to make git "forget" about it. https://stackoverflow.com/questions/1274057/how-to-make-git-forget-about-a-file-that-was-tracked-but-is-now-in-gitignore https://github.com/esajdak/customCrafts/blob/e87b8bba8dca5ceb89fb77929d7714738c7bc768/src/main/resources/hibernate.cfg.xml#L12-L13
