### ISSUE TITLE
Week 6 exercise

### ISSUE THREAD

**Issue by esajdak** [esajdak/customCrafts#8]
@pawaitemadisoncollege week 6 exercise was completed for my project, added the link in the student repo. (I created a temporary jsp to display data from the database for now)

**Comment by pawaitemadisoncollege** [comment]
Excellent!  

-[ ] I know this is just a temporary page, but remember in your "real" jsps to use expression language and jstl rather than scriptlet code like this: https://github.com/esajdak/customCrafts/blob/e87b8bba8dca5ceb89fb77929d7714738c7bc768/src/main/webapp/userResults.jsp#L29-L36

Here's an example of expression language and jstl from the user display exercise solution:

        <c:forEach var="user" items="${users}">
            <tr>
                <td>${user.firstName} ${user.lastName}</td>
                <td>${user.userName}</td>
                <td>${user.age}</td>
            </tr>


        </c:forEach>

Sorry that I did not catch this in your week 2 work!
